### ISSUE TITLE
Reduce gap between fields?

### ISSUE THREAD

**Issue by cmcfadden** [UMN-LATIS/elevator-ui#39]
I feel like we can get away with less vertical padding between fields, so that more content is above the fold. Doing a gap-4 instead of gap-8 still feels like plenty of padding to me. Thoughts?

**Gap 8:**
<img width="347" alt="Screenshot 2022-11-05 at 12 17 08 PM" src="https://user-images.githubusercontent.com/211655/200117252-abde054f-bf96-45eb-975b-13e2e1fdc465.png">

**Gap 4:**
<img width="354" alt="Screenshot 2022-11-05 at 12 16 10 PM" src="https://user-images.githubusercontent.com/211655/200117253-ad778513-b3ff-4434-bfc6-f9d4ef851f0b.png">

**Comment by cmcfadden** [comment]
Kat votes for gap-6, splitting the difference.

**Comment by jxjj** [comment]
A lot of these design decisions are subjective. I'd rather not hash out each one as a github issue.

How about this: I'm already working on tokenizing these design choices as CSS vars so that they can be adjusted in themes. I'll just add this one to the list, and switch the default to 1.5rem (gap-6).

Once the theme support is done, we should be able to quickly setup themes for instances, without needing to write a bunch of custom CSS. [Some ideas here](https://www.figma.com/file/sN61wd3uVahZpdytdbpOBd/Elevator-UI-Refresh?node-id=369%3A5211):
<img width="1093" alt="Screenshot 2022-11-06 at 13 43 36@2x" src="https://user-images.githubusercontent.com/980170/200191570-d295fd11-80ba-4f27-a9cc-fc65151063bc.png">

We should definitely have a McFadden theme available for those that want maximal information density.
